language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    # TODO: Remove it when fixed
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION="3.0.x-dev as 2.8"
  allow_failures:
    - php: 7.0
    - php: nightly
    - php: hhvm
    - env: SYMFONY_VERSION=2.8.*@dev
    - env: SYMFONY_VERSION="3.0.x-dev as 2.8"
    # TODO: Remove those two line when test will be fixed.
    - env: COMPOSER_FLAGS="--prefer-lowest"

services:
  - mongodb

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit --no-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - if ([ "hhvm" != "$TRAVIS_PHP_VERSION" ] && [ "nightly" != "$TRAVIS_PHP_VERSION" ]); then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make test

after_script:
  - if ([ "hhvm" != "$TRAVIS_PHP_VERSION" ] && [ "nightly" != "$TRAVIS_PHP_VERSION" ]); then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;

notifications:
  email: false
